spring:
  application:
    name: discoveryService
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms: 500
  console:
    enabled: true
server:
  port: 8761
